### ISSUE TITLE
Use's password overwritten on server boot?

### ISSUE THREAD

**Issue by adam-cowley** [Multicolour/multicolour#100]
For some reason Waterline is overwriting a hashed password with a hash of the hashed password on init.  Proposed solution would be to add a check to see if the password is already hashed, maybe by checking the length?  There must be a more bulletproof solution though.

libs/user-model.js
```
function hash_password(values, next) {
  // If no password was provided, just move on and exit.
  if (!values.password || values.password.length > 1000) {
    return next()
  }
```

**Comment by davemackintosh** [comment]
I think this is actually an issue in the jwt module itself. Closing as invalid.
