### ISSUE TITLE
Replace sha1 password hashing in initialisation template

### ISSUE THREAD

**Issue by molovo** [Multicolour/multicolour#115]
The `sha1` hashing used [here](https://github.com/Multicolour/multicolour/blob/master/init/content/blueprints/example.js#L29) is nowhere near secure enough for modern day applications, and should be changed.

At a minimum `sha256` or `sha512` should be used, as they are included in node's [built-in crypto library](https://nodejs.org/api/crypto.html#crypto_class_hash), but preferably the [Blowfish (bcrypt)](https://en.m.wikipedia.org/wiki/Blowfish_(cipher)) algorithm could be included via an npm package without too much effort.

Although most responsible developers will replace this with their own security anyway, the temptation is still there for the default to be left in place, so I think it's worth making it [secure by default](https://en.m.wikipedia.org/wiki/Secure_by_default).

Happy to submit a pull request myself if you agree with the above.

**Comment by davemackintosh** [comment]
Agreed, looks like a lazy typo actually. A PR would be most appreciated pal!

**Comment by davemackintosh** [comment]
To clarify, I don't ever want to include bcrypt into a project as I've never had out of the box success installing it.

**Comment by davemackintosh** [comment]
Scheduled for the 0.4.8 maintenance release :+1:

**Comment by davemackintosh** [comment]
Realised in my half asleep state this morning that this is not a user model per say, if you are using one of the auth plugins ([JWT](https://github.com/Multicolour/multicolour-auth-jwt) or [OAuth](https://github.com/Multicolour/multicolour-auth-hapi-oauth) this model is created for you using the core user model which uses the equally secure but NIST recommended PBKDF2 with a configurable iteration count https://github.com/Multicolour/multicolour/blob/master/lib/utils.js#L14-L40

**Comment by molovo** [comment]
Ah, didn't see that helper. I don't think it's worth updating that, PBKDF2 is pretty secure, and would mean a breaking change for little benefit. Might be worth revisiting at the next major release though.

If you're happy then, I'll update the example model to use `utils.hash_password` with salt instead of the `sha1` hash.

**Comment by davemackintosh** [comment]
Yep, that works for me.  Thanks for your time on this and the report 👍

**Comment by davemackintosh** [comment]
Thanks for that @molovo, will be published on the 21st (I think that's my next scheduled maintenance release)

**Comment by davemackintosh** [comment]
Published a couple days late but published in 0.4.8 :+1: 

Thanks for your time @molovo! ❤
