### ISSUE TITLE
npm ERR! notarget No compatible version found: multicolour-seed@^0.1.0

### ISSUE THREAD

**Issue by 750430** [Multicolour/multicolour#130]
Hi.

Just trying to get started with Multicolour and after following [this](https://getmulticolour.com/examples/) getting started guide, I select an authentication method of either Twitter, Google, LinkedIn or JWT, I see this message:
`npm ERR! Darwin 16.1.0`
`npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "install"`
`npm ERR! node v7.2.1`
`npm ERR! npm  v3.10.9`
`npm ERR! code ETARGET`

`npm ERR! notarget No compatible version found: multicolour-seed@^0.1.0`
`npm ERR! notarget Valid install targets:`
`npm ERR! notarget 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1`
`npm ERR! notarget`
`npm ERR! notarget This is most likely not a problem with npm itself.`
`npm ERR! notarget In most cases you or one of your dependencies are requesting`
`npm ERR! notarget a package version that doesn't exist.`
`npm ERR! notarget`
`npm ERR! notarget It was specified as a dependency of '1'`
`npm ERR! notarget`

I have tried `npm install multicolour-seed@0.0.6`but the tree view post install gives `multicolour-seed@0.0.6  invalid`

I also had to manually install: `multicolour-auth-jwt` due to:
`WARN deprecated multicolour-auth-jwt@1.0.0: Package abandoned, contact support@npmjs.com for more info.`

Any assistance would be greatly appreciated!

**Comment by davemackintosh** [comment]
@750430 Let me take a quick look for you!

**Comment by davemackintosh** [comment]
It looks like a typo in the `multicolour init` routine, luckily I've got a scheduled maintenance release for just a couple hours time.

RE the second issue, I unpublished (with the help from the NPM team) the multicolour-auth-jwt module as the name was misleading (future plans for other server frameworks) and the package has been renamed to  `multicolour-hapi-jwt`.

I will roll both fixes into the release shortly. Thanks for reporting and your time! Don't forget to check out the Slack channel where I can help out in real time :+1: 

Thanks again!

**Comment by 750430** [comment]
Cor! super fast! Many thanks! I had a quick look around on the Multicolour site, I didn't notice a link to a Slack group sign up... it's been a long day already 👍

**Comment by davemackintosh** [comment]
Ha, I know the feeling. Here's the link https://slack.getmulticolour.com/

I'll make sure to add a link to it in the next update (tomorrow with better documentation)

**Comment by davemackintosh** [comment]
Both of these issues are resolved locally, will publish shortly. :+1: Thanks again for your time using Multicolour and reporting this issue. Software is improved by finding and fixing bugs and it's great appreciated doing one, the other or both. :+1:

**Comment by davemackintosh** [comment]
Ahh the call of paid work, will publish these fixes first thing in the morning.
