### ISSUE TITLE
Create basic theme for front-end.

### ISSUE THREAD

**Issue by davemackintosh** [Multicolour/multicolour#16]

**Comment by Sogl** [comment]
:+1:

**Comment by davemackintosh** [comment]
https://github.com/Multicolour/multicolour-frontend-polymer

**Comment by Sogl** [comment]
Cool. Do you have plans to add it in `multicolour-example`?

**Comment by davemackintosh** [comment]
Once the build is finished I will be adding it to the example app :)

**Comment by davemackintosh** [comment]
I'm removing this from the 0.4.0 milestone. I will blog why soon.
