### ISSUE TITLE
SQLite 3 adapter needs prepublish running

### ISSUE THREAD

**Issue by davemackintosh** [Multicolour/multicolour#176]
Until this PR is merged we have to use a github url to install adapter

https://github.com/waterlinejs/sqlite3-adapter/pull/19

But it requires a compilation step for some reason.

**Comment by ShaneHudson** [comment]
"compilation step" What's needed to get this running? I just kept getting cannot find module despite using your fork url.

**Comment by davemackintosh** [comment]
Currently (i shall push a fix for it tonight) `cd node_modules/waterline-sqlite/ && npm run prepublish` should do it
