### ISSUE TITLE
CLI and the American Spelling of Color

### ISSUE THREAD

**Issue by jbolda** [Multicolour/multicolour#207]
> `multicolor init` would be a frequent error for most people using this.
> 
> The spelling of color there. For most APIs, developer tools I think it's more common to use the American spelling over the brit spelling.

via @bl4ckdu5t.

It may be helpful to add support for `color` as well.

**Comment by davemackintosh** [comment]
Great idea, have scheduled for 0.6.5 on Monday :+1: :muscle:

**Comment by davemackintosh** [comment]
To go a little further on this, I've also published an American friendly npm package https://www.npmjs.com/package/multicolor

**Comment by bl4ckdu5t** [comment]
Great @davemackintosh
