### ISSUE TITLE
Default user plugin :: password should be stored in database, not in plugin

### ISSUE THREAD

**Issue by ShaneHudson** [Multicolour/multicolour#224]
### Versions

What is the output of:

1. `multicolour version` 0.6.6
2. `node -v` v7.8.0
3. `npm list --depth=0`
```
├── joi@10.4.1
├── multicolour@0.6.6
├── multicolour-auth-oauth@1.2.3 extraneous
├── multicolour-server-hapi@1.7.7
└── sails-memory@0.10.7

npm ERR! extraneous: multicolour-auth-oauth@1.2.3 /Users/shanehudson/Development/Projects/nextline-codebase/node_modules/multicolour-auth-oauth
npm ERR! peer dep missing: hapi@^14.0.0 || ^15.0.0 || ^16.0.0, required by hapi-swagger@7.7.0
```

### Expected behavior

When I entered my password into the wizard, it used asterisks. So I presumed it was somewhat safe.

### Actual behavior

The default-person plugin has my password in plaintext. If this is required, then maybe wizard should either create a random password or specifically say it will be stored in the codebase.

### Steps to reproduce behavior

Run `multicolour init .` and enter password.

**Comment by davemackintosh** [comment]
Going to push this into 0.6.8

**Comment by davemackintosh** [comment]
A notice was added to the CLI, I've also improved the general language of the init command (and added some new stuff to it)
