### ISSUE TITLE
Issues killing process with ctrl-c

### ISSUE THREAD

**Issue by benfoxall** [Multicolour/multicolour#241]
Since updating to 0.6.7, ctrl-c doesn't seem to kill the server.  (I'm running it locally just straight with node, no pm2).

### Versions

What is the output of:

1. `multicolour version` - **0.6.7**
2. `node -v` - **v7.7.4**
3. `npm list --depth=0`

```
├── multicolour@0.6.7
├── multicolour-hapi-jwt@0.1.4
├── multicolour-hapi-vantage@1.0.1
├── multicolour-server-hapi@1.7.7
```

### Expected behavior

When I hit `ctrl-c`, I expect things to clean up, then shut down.

### Actual behavior

When I hit `ctrl-c` I see this message:

```
^CAll services going away. CLI will be handed back immediately but services may continue to shut down in background.
[…some services stop]
Server stopped running at: http://Bens-MBP:1911
All services stopped successfully.
```

though nothing seems happen. When I do it again, the exact same message appears

### Steps to reproduce behaviour

1. Start the app
2. Try to stop it

**Comment by davemackintosh** [comment]
Thanks for the report @benfoxall! This appears to be related to #240 and #232. Is fixed in [this commit](https://github.com/Multicolour/multicolour/commit/9742cbc866f55d34c8a955235d56ce5b6a050fe7)

I will mark as duplicate and close as 0.6.8 is due to be published on Friday. :+1:

**Comment by benfoxall** [comment]
Just upgraded and working fine again 👍
