### ISSUE TITLE
Mongodb kerberos peer dependency

### ISSUE THREAD

**Issue by Sogl** [Multicolour/multicolour#40]
Hi!
After `npm i`:
```
┬ sails-mongo@0.11.7 
├── async@1.5.2 
├─┬ mongodb@2.1.3 
│ ├── es6-promise@3.0.2 
│ ├── UNMET PEER DEPENDENCY kerberos@~0.0
│ ├─┬ mongodb-core@1.2.31 
│ │ └── bson@0.4.21 
│ └── readable-stream@1.0.31 
└── validator@4.5.1 
```

I don't use Mongo at all, but can you solve this problem?

What I've found:
https://stackoverflow.com/questions/33642666/mongodb-kerberos-peer-dependency

node 4.2.1
npm 3.5.3
OS X 10.10.5

**Comment by davemackintosh** [comment]
It's just a warning, mongo should be installed https://jira.mongodb.org/browse/NODE-612
