### ISSUE TITLE
User parameters string is very long in Swagger

### ISSUE THREAD

**Issue by Sogl** [Multicolour/multicolour#41]
In `/docs`:

![image](https://cloud.githubusercontent.com/assets/7556290/12695249/6368e618-c78b-11e5-8635-eae9a8a247a3.png)

Tested in Chrome and Firefox last versions.

**Comment by davemackintosh** [comment]
I've been aware of this for a while, I'll look into whether it can be resolved or whether this pushes me over the edge with hapi-swaggered.

**Comment by davemackintosh** [comment]
Related: #45
