### ISSUE TITLE
Replace hapi-swaggered-ui

### ISSUE THREAD

**Issue by davemackintosh** [Multicolour/multicolour#45]

**Comment by davemackintosh** [comment]
Candidate https://github.com/hapijs/lout

**Comment by Sogl** [comment]
Swagger looks much better than lout... and also you can test API with it.

**Comment by davemackintosh** [comment]
Agreed. but the hapi-swagger-ui module has many bugs and the repo doesn't move very fast. I want to find either a less buggy Swagger UI module or another solution.

**Comment by davemackintosh** [comment]
Sticking with Swagger but using the `hapi-swagger` module instead as it has less bugs. The module also fixes #41

**Comment by davemackintosh** [comment]
This issue is blocked by https://github.com/glennjones/hapi-swagger/issues/235

**Comment by davemackintosh** [comment]
Progress on https://github.com/glennjones/hapi-swagger/issues/235 unblocks this issue for now. Still waiting for an issue to be resolved and publish but can continue dev.
