### ISSUE TITLE
Create more advanced frontend generator - Poll!

### ISSUE THREAD

**Issue by davemackintosh** [Multicolour/multicolour#57]
Another front-end generator would be rad, there's a heap of technologies out there though so here is a list of ones I like, add a comment with your favourite.

Closes when 0.4.0 is released in April.
- [Elm](http://elm-lang.org/)
- [Mercury](https://github.com/Raynos/mercury)
- [ReactJS](https://facebook.github.io/react/)
- [Backbone](http://backbonejs.org/)

I've intentionally not listed Angular or Ember here because personally their performance just isn't up to scratch. If the outcry is loud enough, it can be considered but it can also always be created by the community.

**Comment by Sogl** [comment]
Backbone or ReactJS I think :+1:

**Comment by davemackintosh** [comment]
I'm all for React

**Comment by juice49** [comment]
React!
